
trigger:
- master

pr:
  autoCancel: true
  branches:
    include:
      - master

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build for master
  branches:
    include:
      - master

jobs:
- job: BleedingMoSDeF
  strategy:
    matrix:
      Python37Ubuntu:
        imageName: 'ubuntu-latest'
        python.version: 3.7
      Python37macOS:
        imageName: 'macOS-latest'
        python.version: 3.7
      #Python36Ubuntu:
      #  imageName: 'ubuntu-latest'
      #  python.version: 3.7
      #Python36macOS:
      #  imageName: 'macOS-latest'
      #  python.version: 3.6

  pool:
    vmImage: $(imageName)

  steps:
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add Conda to path

    - bash : echo "##vso[task.prependpath]$(Build.SourcesDirectory)/mosdef_cassandra/tests/files/Cassandra_V1.2/bin"
      displayName: Add Cassandra to path

    - bash: |
        sudo apt-get update
        sudo apt-get install gfortran
        gfortran --version
      displayName: Install gfortran Linux
      condition: eq( variables['Agent.OS'], 'Linux' )

    - bash: |
        brew install gcc
        brew upgrade gcc
        gfortran --version
      displayName: Install gfortran macOS
      condition: eq( variables['Agent.OS'], 'Darwin' )

    - bash: |
        cd mosdef_cassandra/tests/files/
        tar -xzvf Cassandra_V1.2.tar.gz
        cd Cassandra_V1.2/Src
        make -f Makefile.gfortran
        mkdir ../bin
        cp cassandra_gfortran.exe ../bin/.
        cp ../Scripts/Frag_Library_Setup/library_setup.py ../bin/.
        cd ../../../../../
      displayName: Build Cassandra

    - bash: |
        echo Working directory:
        pwd
        echo ls:
        ls
        echo PATH:
        echo "$PATH"
        echo CASSANDRA:
        which cassandra_gfortran.exe
        echo PYTHON2
        which python2
        echo LIBRARY_SETUP:
        which library_setup.py
      displayName: Check cassandra install
