# ReadTheDocs uses the `environment.yaml` so make sure to update that as well
# if you change the dependencies of JupyterHub in the various `requirements.txt`
name: mc-docs
channels:
  - https://metachannel.conda-forge.org/conda-forge/cassandra,mosdef_cassandra,mbuild,numpy,parmed
  - mosdef
  - omnia
dependencies:
  - python=3.7
  - numpy
  - parmed
  - mbuild >= 0.10.5
  - foyer >= 0.7.3
  - cassandra >= 1.2.2
  - pip
  - pip:
    - sphinx
    - sphinx_rtd_theme
    - networkx
